import { Nav } from "@/components/nav"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import { ViewTransitions } from "next-view-transitions"
import { PropsWithChildren } from "react"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <ViewTransitions>
      <html lang="en" className="bg-black">
        <body
          className={`${GeistSans.className} relative bg-[#0c0c0c] before:absolute before:inset-0 before:bg-[url('/grain.png')] before:bg-repeat before:opacity-[3%] `}
        >
          <Nav />
          {children}
        </body>
      </html>
    </ViewTransitions>
  )
}
